// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import FlashItemController from './flash_item_controller'
import NavController from './nav_controller'
import UploadsController from './uploads_controller'

application.register('flash-item', FlashItemController)
application.register('nav', NavController)
application.register('uploads', UploadsController)
