// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import DetailsAutoOpenController from './details_auto_open_controller'
import FlashItemController from './flash_item_controller'
import FormNavController from './form_nav_controller'
import JumpToController from './jump_to_controller'
import LivesearchController from './livesearch_controller'
import MarkdownRendererController from './markdown_renderer_controller'
import MoreOptionsController from './more_options_controller'
import NavController from './nav_controller'
import SlimSelectController from './slim_select_controller'
import SearchResultsController from './search_results_controller'
import SettingsController from './settings_controller'
import TableEditorController from './table_editor_controller'
import ToggleController from './toggle_controller'
import UploadsController from './uploads_controller'

application.register('details-auto-open', DetailsAutoOpenController)
application.register('flash-item', FlashItemController)
application.register('form-nav', FormNavController)
application.register('jump-to', JumpToController)
application.register('livesearch', LivesearchController)
application.register('markdown-renderer', MarkdownRendererController)
application.register('more-options', MoreOptionsController)
application.register('nav', NavController)
application.register('slim-select', SlimSelectController)
application.register('search-results', SearchResultsController)
application.register('settings', SettingsController)
application.register('table-editor', TableEditorController)
application.register('toggle', ToggleController)
application.register('uploads', UploadsController)
