module AppConfig
  # Required configs
  TYPESENSE_SEARCH_API_KEY = ENV.fetch("TYPESENSE_SEARCH_API_KEY")
  TYPESENSE_API_KEY = ENV.fetch("TYPESENSE_API_KEY")
  TYPESENSE_HOST = ENV.fetch("TYPESENSE_HOST")
  TYPESENSE_PORT = ENV.fetch("TYPESENSE_PORT")
  TYPESENSE_PROTOCOL = ENV.fetch("TYPESENSE_PROTOCOL")
  SECRET_KEY_BASE = ENV.fetch("SECRET_KEY_BASE")

  # Optional configs
  YOUTUBE_API_KEY = ENV["YOUTUBE_API_KEY"]
end
