default: &default
  auto_sync:
    class: AutoSyncJob
    schedule: every hour
  auto_purge:
    class: AutoPurgeJob
    schedule: every hour
  prune_unconfirmed_users:
    class: PruneUnconfirmedUsersJob
    schedule: every day at noon

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
