default: &default
  auto_sync:
    class: AutoSyncJob
    schedule: every hour
  auto_purge:
    class: AutoPurgeJob
    schedule: every hour

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
